# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'commonmodule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for commonmodule
  pod 'OSAMCommon', :git => 'git@gitlab.dtibcn.cat:osam/common_module_mobile_frameworks.git', :tag => '1.0.6'
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

end
